version: '3.7'
services:
  db:
      image: postgres:15.4
      volumes:
        - ./tmp/db:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=postgresPasswword
        - POSTGRES_USER=nodeProdUser
        - POSTGRES_DB=node_pretaa_testing
      ports:
        - '5432:5432'